# Generated by Django 3.2.20 on 2025-03-28 18:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('BOOK', 'Book'), ('SHOE', 'Shoe'), ('ELECTRONIC', 'Electronic'), ('CLOTHING', 'Clothing'), ('HOME_APPLIANCE', 'Home Appliance'), ('FURNITURE', 'Furniture'), ('BEAUTY', 'Beauty & Personal Care'), ('FOOD', 'Food & Beverage'), ('SPORTS', 'Sports & Outdoors'), ('TOYS', 'Toys & Games'), ('AUTOMOTIVE', 'Automotive'), ('PET_SUPPLIES', 'Pet Supplies'), ('HEALTH', 'Health & Wellness'), ('OFFICE', 'Office Supplies'), ('MUSIC', 'Musical Instruments')], max_length=50)),
                ('category_path', djongo.models.fields.JSONField(default=list)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('attributes', djongo.models.fields.JSONField(default=dict)),
                ('primary_image', models.URLField()),
                ('image_urls', djongo.models.fields.JSONField(blank=True, default=list)),
                ('seller_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('OUT_OF_STOCK', 'Out of Stock'), ('DISCONTINUED', 'Discontinued'), ('PRE_ORDER', 'Pre-Order'), ('BACK_ORDER', 'Back Order'), ('LIMITED', 'Limited Edition'), ('EXPIRED', 'Expired'), ('RESTRICTED', 'Restricted'), ('BANNED', 'Banned')], default='DRAFT', max_length=20)),
                ('total_views', models.IntegerField(default=0)),
                ('total_sold', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensions', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('tags', djongo.models.fields.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sold_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_sku_fe2039_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='products_product_af48aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_status_a30e64_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller_id'], name='products_seller__c70854_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['total_sold'], name='products_total_s_9cf035_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_brand_b2547a_idx'),
        ),
    ]
