# Generated by Django 3.2.20 on 2025-03-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('OUT_OF_STOCK', 'Out of Stock'), ('DISCONTINUED', 'Discontinued'), ('PRE_ORDER', 'Pre-Order'), ('BACK_ORDER', 'Back Order'), ('LIMITED', 'Limited Edition'), ('EXPIRED', 'Expired'), ('RESTRICTED', 'Restricted'), ('BANNED', 'Banned')], default='ACTIVE', max_length=20),
        ),
    ]
