# Generated by Django 4.2.7 on 2025-03-29 22:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(db_index=True)),
                ('method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('vnpay', 'VNPay'), ('momo', 'Momo'), ('bank', 'Chuyển khoản ngân hàng'), ('paypal', 'PayPal')], max_length=20)),
                ('payment_gateway', models.CharField(help_text='Cổng thanh toán (VNPay, Momo, PayPal, v.v.)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('refunded', 'Đã hoàn tiền'), ('partially_refunded', 'Hoàn tiền một phần')], default='pending', max_length=20)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_proof', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Lưu thông tin bổ sung của cổng thanh toán', null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('refunded', 'Đã hoàn tiền'), ('partially_refunded', 'Hoàn tiền một phần')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payment.payment')),
            ],
        ),
    ]
