apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-service
  namespace: microservices
  labels:
    app: sentiment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sentiment-service
    spec:
      containers:
        - name: sentiment-service
          image: ${DOCKERHUB_USERNAME}/sentiment-service:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "5000"
            - name: DEBUG
              value: "False"
            - name: API_VERSION
              value: "v1"
            - name: REVIEW_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: sentiment-service-config
                  key: review_service_url
            - name: REVIEW_SERVICE_TIMEOUT
              value: "10"
            - name: REPORTS_DIR
              value: "/app/reports/sentiment_analysis"
            - name: CORS_ORIGINS
              value: "*"
            - name: CACHE_ENABLED
              value: "True"
            - name: CACHE_TTL
              value: "3600"
            - name: LOG_LEVEL
              value: "INFO"
          volumeMounts:
            - name: reports-volume
              mountPath: /app/reports
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: reports-volume
          emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-service
  namespace: microservices
  labels:
    app: sentiment-service
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: sentiment-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentiment-service-ingress
  namespace: microservices
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - sentiment.${DOMAIN_NAME}
      secretName: sentiment-tls
  rules:
    - host: sentiment.${DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentiment-service
                port:
                  number: 5000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sentiment-service-hpa
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sentiment-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80 