# Generated by Django 3.2.20 on 2025-03-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex')], max_length=10)),
                ('sport_type', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('closure_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sole_material', models.CharField(blank=True, max_length=100, null=True)),
                ('upper_material', models.CharField(blank=True, max_length=100, null=True)),
                ('waterproof', models.BooleanField(default=False)),
                ('breathability', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('recommended_terrain', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty_period', models.IntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shoes',
            },
        ),
        migrations.AddIndex(
            model_name='shoe',
            index=models.Index(fields=['product_id'], name='shoes_product_d9c8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='shoe',
            index=models.Index(fields=['size'], name='shoes_size_02ea16_idx'),
        ),
        migrations.AddIndex(
            model_name='shoe',
            index=models.Index(fields=['color'], name='shoes_color_eb06b8_idx'),
        ),
        migrations.AddIndex(
            model_name='shoe',
            index=models.Index(fields=['sport_type'], name='shoes_sport_t_4f82c0_idx'),
        ),
    ]
