# Generated by Django 3.2.20 on 2025-03-01 18:16

import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('pages', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dimensions', djongo.models.fields.JSONField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('additional_images', djongo.models.fields.JSONField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_featured', models.BooleanField(default=False, null=True)),
                ('tags', djongo.models.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category', 'author'], name='books_categor_5b7c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='books_price_89e2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['rating'], name='books_rating_1c0f51_idx'),
        ),
    ]
