name: Sentiment Service CD

on:
  workflow_run:
    workflows: ["Sentiment Service CI"]
    branches: [main, develop]
    types: [completed]

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}
    environment: staging
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Set up kubeconfig
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_STAGING }}
    
    - name: Update deployment image
      working-directory: ./sentiment-service/k8s
      run: |
        kubectl set image deployment/sentiment-service sentiment-service=${{ secrets.DOCKERHUB_USERNAME }}/sentiment-service:develop
    
    - name: Verify deployment
      working-directory: ./sentiment-service/k8s
      run: |
        kubectl rollout status deployment/sentiment-service
    
    - name: Notify deployment status
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: deployments
        SLACK_TITLE: Staging Deployment
        SLACK_MESSAGE: "Sentiment Service deployed to staging :rocket:"
        SLACK_COLOR: ${{ job.status }}

  deploy-to-production:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    environment: production
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Set up kubeconfig
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_PRODUCTION }}
    
    - name: Update deployment image
      working-directory: ./sentiment-service/k8s
      run: |
        kubectl set image deployment/sentiment-service sentiment-service=${{ secrets.DOCKERHUB_USERNAME }}/sentiment-service:main
    
    - name: Verify deployment
      working-directory: ./sentiment-service/k8s
      run: |
        kubectl rollout status deployment/sentiment-service
    
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: sentiment-v${{ github.run_number }}
        release_name: Sentiment Service Release v${{ github.run_number }}
        draft: false
        prerelease: false
    
    - name: Notify deployment status
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: deployments
        SLACK_TITLE: Production Deployment
        SLACK_MESSAGE: "Sentiment Service deployed to production :rocket:"
        SLACK_COLOR: ${{ job.status }} 